scaleout: 200
chunksize: 50000
mem-per-worker: "1GB"
disk-per-worker: "1GB"
queue: "long"
walltime: "5-00:00:00"
adaptive: false
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
spanet_model: "/pnfs/psi.ch/cms/trivcat/store/user/mmarcheg/ttHbb/models/meanloss_multiclassifier_btag_LMH/spanet_output/version_0/spanet.onnx"
