plotting_style:
    efficiency:
        2016_PostVFP:
            Ele32_EleHT_pass:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_highHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_lowHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
        2016_PreVFP:
            Ele32_EleHT_pass:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_highHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_lowHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
        '2017':
            Ele32_EleHT_pass:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_highHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_lowHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
        '2018':
            Ele32_EleHT_pass:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_highHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
            Ele32_EleHT_pass_lowHT:
                ElectronGood_eta:
                    ylim:
                    - 0
                    - 1
                ElectronGood_etaSC:
                    ylim:
                    - 0
                    - 1
                ElectronGood_phi:
                    ylim:
                    - 0
                    - 1
                ElectronGood_pt:
                    ylim:
                    - 0
                    - 1
                ht:
                    ylim:
                    - 0
                    - 1
                nJets:
                    ylim:
                    - 0
                    - 1
